README.md
Link for http://deeplearning.net/software/theano/ should be added.
Also, please add label for hackoberfest.
=> wiki: link added

tensor/f64/matop_test.go
=> Convert TestTRepeat to table driven test

collections_test.go, gorgonia.go, node.go, node_test.go, op_test.go, operations.go, tensor/b/perf.go, tensor/f32/perf.go, tensor/f64/perf.go, tensor/i/perf.go, typeSystem_test.go
Added documentation for the previously unexported construction options
=> Fixes #77. 

collections.go, op_tensor.go, operations.go, operations_test.go, perf.go, typeSystem.go, vm_genera.go, vm_genera_test.go
Fixes #92 and adds a few perf optimiazations
=> Issue92fix

tensor/consopt.go, tensor/dense.go, tensor/dense_io.go, tensor/genlib/dense_io.go
refactored the masked tensor construction - removed the need for (...[]bool), instead, added an additional `addMask()` method.
=> Refactor mask

examples/charRNN/model.go
=> Remove unnecessary logging

gorgonia.go, gorgonia_test.go
Make OneHotVector Great Again.
=> Fix OneHotVector

solvers.go, solvers_test.go
=> Add momentum sgd algorithm

solvers.go
=> Fix Momentum

op_reduction.go, op_reduction_test.go
Hi,
I modified opMax.InferShape, opMax.Do
and added TestMax
it's probably a bit naïve but it does work for me on CPU
Best regards
=> Attempt to fix Max

CONTRIBUTORS.md
=> Updated contributors list.

known_issues_test.go, op_nn.go
This patch fix MaxPool2D output shape calculation.
Fixes: #273
=> Fix MaxPool2D output shape

broadcast.go, broadcast_test.go, op_reduction.go, operations.go
I propose a new API as discussed in [issue #223](https://github.com/gorgonia/gorgonia/issues/223).
The tests are ok, and the benchmark does not mark any regression.
I have tested the implementation against this branch of [onnx-go](https://github.com/owulveryck/onnx-go/blob/gorgonia-broadcast/backend/x/gorgonnx/ONNX_COVERAGE.md) and the integration tests are all passing.
There should not be any regression, but I'd like your opinion about the implenentation in the function:
https://github.com/gorgonia/gorgonia/blob/abe81aeb2b4478a55ae7bc73859a8759c8cd5688/op_reduction.go#L73
Is it ok to set a `retSame` to `false` in this code: https://github.com/gorgonia/gorgonia/blob/abe81aeb2b4478a55ae7bc73859a8759c8cd5688/op_reduction.go#L96
=> New broadcasting API

examples/286/main.go, operations.go
Updated `Div` such that it will check to see if both operands are the same shape and thus use HadamardDiv
fixes #286
=> fixes #286

batch.go, bitmap.go, blas.go, complex_test.go, cuda.go, debug.go, device.go, differentiation_test.go, engine.go, errors.go, execution.go, graph.go, interfaces.go, nn.go, noextern.go, op.go, op_math_noextern.go, op_nn.go, operations.go, release.go, solvers.go, type.go, utils.go, vm.go, walker.go, weights.go
The purpose of this PR is to do small fixes pointed by the linter.
Most of them are about documentation.
see https://go-lint.appspot.com/gorgonia.org/gorgonia
=> small fixes pointed by golint

cuda/arena.go, cuda/engine.go, cuda/external.go, cuda/linalg.go
Improve gorepord by adding documentation to `cuda` package methods.
#328
=> Add method documentation to cuda package

ermagerdmonards.go
The underlying type is now gErr. It implements Result and error.
=> Changed `Err{}` to be a function instead.

operations_test.go
Adding a unit test for activation function Mish.
Testing non-monotonicity property of Mish and
Mish's derivative.
=> Adding test for activation function Mish

nn.go, nn_test.go
Resolves #387 
I also extracted the `Dropout` function into a private `dropout` function so I can inject my own "random" numbers during tests.
Let me know if I need to change anything. :+1:
=> Fix Dropout() to return corrrect scaled output

op_tensor.go, op_tensor_test.go
=> fix(415): atOp's writeHash doesn't panic anymore

nn.go
Check all padding (N S E W), kernel and input size to avoid index out of range
=> MaxPool2D checks (#435)

op_sparsemax.go, op_sparsemax_test.go
It implement the methods necessary to run a backpropagation on this
operation.
=> Implement ADOp and SDOp for the sparseMax operation

operations.go, operations_test.go
It's the same as Flatten, it converts a n-rank tensor to 1-rank tensor
=> Add Ravel function

operations.go, operations_test.go
=> Ravel now returns an error

op_upsample.go
=> Differentiation OP for Upsample node

go.mod, go.sum, nn.go, nn_test.go
It has better error handling and checks for correct shapes giving more
useful information to the user to debug shaping issues
=> Add a bunch of checks to the Conv2d function

op_sparsemax.go, op_sparsemax_test.go
And support any dimension for the input
=> Make sparsemax an axial operation

operations.go, operations_broadcast_test.go, operations_test.go
For example:
Auto(BroadcastHadamardProd(a, b))
=> Implement auto broadcasting

weights.go
Just a simple fix to a wrong panic message I stumbled upon.
=> Fix panic message

nn.go, nn_test.go, op_avg_pool.go, op_avg_pool_test.go, op_nn.go
This branch also includes 2 bugfixes for maxpool:
- crash when using a shape without checking its dims first
- crash when the calculated strides are empty
=> Implement average pool 1d and 2d operations

op_softmax.go
=> Fix the typo in index for softmax gradient calculation
