gorgonia/gorgonia

README.md
Wanted:
- Consistent `if err != nil {` styles. (Lines 76-77 now match 82-83)
- Copy, Paste, Install & Run: so added the missing `package main`.
As I was confused when reading through.
**Update**: Noticed there were other example on the README let me know if I should update those to this format also.
=> Updated README example for readability

blase/fn.go, cmd/cudagen/main.go, node.go, tensor/dense_svd_test.go, tensor/tensor.go, typeSystem_test.go, vm_genera_test.go
In anticipation of 1.0, some of the lively language in the comments were
toned down a wee bit.
=> Clean up language in the code

CONTRIBUTORS.md, README.md
Added @siquus  to list of contributors (no name given, no name can be inferred, so github username was used instead)
Added documentation for caffe's licence on `im2col` and `col2im`
=> added contributors and readme

op_tensor_test.go, operatorPointwise_unary_test.go, vm_tape.go
Go is a lot more religious in checking for string interpolation and formatting now.
=> Fixed up the issues that gotip has found

CONTRIBUTORS.md, gorgonia.go, graph.go, node.go
Fixes #177 by adding an optional naming capability - by default fmt.Sprintf will be used but if a name is passed in, then it will be used as the identifier for the constant.
=> #180 redux

.travis.yml, graph.go
Removed pre-go1.8 from travis because Gonum no longer supports pre1.8
=> Fixed a tiny bug in UnbindNonInputs.

cmd/cudagen/main.go
Use go1.10's default gopath if can't find a gopath
=> Use go1.10's default gopath if can't find a gopath

README.md
Fix a broken link in the README and make identical the commented output
of one of the examples shown in the README.
=> README: Fix link & specific output in example

Gopkg.lock, Gopkg.toml, examples/convnet/main.go
To wrap was more thorough commented in commit messages:
1. Remove warning in deps https://github.com/gorgonia/gorgonia/issues/214
2. Updated Gonum in Gopkg ([why not despite of _vgo_ is coming?[(https://github.com/gorgonia/gorgonia/issues/213#issuecomment-401522088))
3. Minor fix in one of the examples
I believe that _2_, is good, although _vgo_ is coming, however if you prefer not to and you want to keep the rest of the commits, let me know and I will drop such commit.
I could make a comment about _1_, before making the change, however, because of the minor change, it was easier to make a commit rather than trying to explain by words on the issue; however, I know that you may prefer other thing, so don't hesitate to comment what to do or reject such commit.
=> Remove waring of dep, update Gonum & minor fix in example

compile.go, const.go, differentiation.go, graph.go, graph_test.go, node.go, regalloc.go
Please take a look.
Fixes #237.
Note that there is a vet failure that I had to fix but is unrelated.
```
./op_tensor.go:1144: Wrapf call has arguments but no formatting directives
```
=> gorgonia: update for changes in gonum/graph iterator API

graph.go
This will be necessary when gonum/gonum#867 is merged.
=> Update graph edge for gonum/graph API change

.travis.yml, perf.go
All of the tests in onnx can run in parallel. 
In this case, every subtest creates a new `ExprGraph`. The problem is that the `dimSizerPool` is not safe for concurrent use (as it is a map) and running several tests in parallel leads to a race condition.
This PR replaces the `map` by a `sync.Map`.
This patch removes the race condition but may have an impact on the performances.
=> use a sync.Map instead of a map for dimSizerPool to prevent race condition

go.mod
It erroneously decides that these must be external and creates a circular reference for any packages that attempt to `go get gorgonia.org/gorgonia`
Closes #277
=> Not using the full path confuses `go mod` for internal `gorgonia.org/gorgonia` imports

benchmark_operations_test.go, op_tensor.go, operations_test.go
This PR is related to #296 
* the `reshapeOP` uses a `ShallowClone` method of the value if it's a `*tensor.Dense`.
* the `OverwriteInput` method returns `-1` because it does not touch the backend values and creates a new entity to work on.
=> Reshape optim

mathutils_go.go
I tested this patch by doing some tests with onnx-go on raspberry pi 3 with golang 1.13/armv6.
=> chore: add noasm for build on armv6

stabilization.go, stabilization_test.go
This is a fix for the following issue:
When there is an operation like Log(x+2), the stabilization will replace it by Log(nil)
See unit test for an example.
Thanks!
=> Fix stabilization for Log(x+k), k!=1

examples/iris/main.go
=> Improvement of example/iris

CONTRIBUTORS.md, LICENSE
Change the license from the Gorgonia license to the Apache 2.0 license to allow for easier automatic recognition of the license.
=> Change license to Apache 2.0 and update contributors list

op_reduction.go, op_reduction_test.go, operations.go, shape_test.go
Fixes reduction bugs while cleaning up some of the code.
* `len(shape)` is to be  discouraged, as future versions of `tensor.Shape` may be more static for performance reasons.
* `reductionInerSahpe` does not require `...DimSizer` as inputs. Instead, now checks are made so that they only take `tensor.Shape`.
The bug being resolved can be described as follows: 
```
func TestSumOpFakeVec(t *testing.T) {
g := NewGraph()
xv := tensor.New(tensor.WithBacking([]float64{1, 2}), tensor.WithShape(2, 1))
yv := tensor.New(tensor.WithBacking([]float64{10, 20}), tensor.WithShape(1, 2))
x := NewMatrix(g, Float64, WithName("x"), WithShape(2, 1), WithValue(xv))
y := NewMatrix(g, Float64, WithName("y"), WithShape(1, 2), WithValue(yv))
sx, _ := Sum(x)
sy, _ := Sum(y)
assert.True(t, …
```
=> Fix reduction bugs

op_tensor.go
This is fixed in two ways:
1. If the input is a `View` then it is materialized. This
requires more memory, but it is more worth it to allocate than to
stress over calculating  how much extra overhead to allocate for
sharing memories
2. `ShallowClone` is fixed in package `tensor` to make sure that
views are correctly shallow cloned as well
=> Fixed a bug in Reshape, where a slice of a slice cannot be reshaped.

known_issues_test.go, operatorPointwise_unary.go
The main problem was in the diff function of `Neg`. It should increment the derivative of x, but a wrong method was called (`UnsafeDo`).
This makes it fail for values that are scalars. This has been fixed.
=> Fixes #363

known_issues_test.go, operations.go
comparison was made against the (n-1)th rank of a tensor, rather than
the nth rank of the tensor.
=> Fixed #368 - the cause is an off-by-one bug in the SoftMax function. A

operatorPointwise_binary.go, operatorPointwise_binary_test.go
Scalar bin ops requires creating a pointer to a scalar when returning the same value type.
=> fix return value as pointer in scalar bin ops

.gitignore, cmd/cudagen/main.go, cuda.go, cuda/builtin.go, cuda_test.go, vm_genera_cuda.go, vm_tape_cuda.go
Closes #380.
- Compilation output is now placed in the system's temp directory and removed afterwards.
- `cudamodules.go` will be placed in the current directory.
- I changed the signature of `AddToStdLib`. It now accepts a list of functions. I assume this function is only used by `cudamodules.go` but because it's an exported function it still breaks the interface.
- Added a flag `-same-module` for when you need to create a `cudamodules.go` file in the gorgonia package (for when you want to run tests with cuda). Updated the `go:generate` directive in the gorgonia package so it will use this flag.
- Removed the commented out nvcc command with the "fast" flags. If you need this I can put it back but behind a flag or something?
- I'm kind of able to run a my own model with this. However, …
=> Make cudagen work with Go modules

examples/mnist/mnist.go
I download mnist data by [`examples/mnist/download.sh`](https://github.com/gorgonia/gorgonia/blob/master/examples/mnist/download.sh), then execute `convnet` example. But  I got following errors:
```
$ ./bin/gorgonia_convnet
2020/04/19 22:10:35 Unable to read Labels: open /Users/a14737/go/src/github.com/c-bata/goptuna/_examples/gorgonia_convnet/data/train-labels.idx1-ubyte: no such file or directory
```
The reason why I got this error is just missed file name. `download.sh` generated a file train-labels-idx1-ubyte, not train-labels.idx1-ubyte. I fix this problem on this pull request.
=> Fix mnist loader

examples/convnet/main.go
convnet example seems to be broken.
```
$ go build -o convnet ./examples/convnet/
examples/convnet/main.go:219:37: undefined: cost
```
https://github.com/gorgonia/gorgonia/blob/cb4f110a9c3a9bbc51339bf8042b039169160ed3/examples/convnet/main.go#L219-L220
So I fix this error. The source code at v0.9.0-beta is following:
https://github.com/gorgonia/gorgonia/blob/978b1c3c0f795d09d0710238cb5f82853b99a460/examples/convnet/main.go#L219-L220
=> Fix convnet example

op_reduction.go, op_reduction_test.go
Partial fix for #323.
This should fix differentiation of the `Max()` op. Until now I had almost no experience with this so please check that the grads I'm asserting are what is supposed to happen. It does seem to work with a model I'm training.
I added 2 commented out tests. These do not work yet but should once #373 is fixed.
If you want I can create the same tests for the `Sum()` op. Let me know if you want that in a separate PR or added to this one.
=> Fix Max() op + tests

differentiation.go, go.sum, node.go, op_reduction.go, op_reduction_test.go, operations.go
The reductionInferShape currently doesn't respect along initially.
It aggressively squeezes dimensions. Not only does it affect normal tensor operation, but also it breaks the backprop autoDiff algorithm sometimes when the network containing BroadcastAdd, resulting in crash when calling Grad().
The change tries to strictly respect the parameter along, e.g.,
(100, 1) along 0, reduction to shape (1) instead ()
(1, 64, 1, 64) along 3 will reduce to (1, 64, 1)
(64, 1, 3, 2) along (2,3) will reduce to (64, 1).
Fixed unit tests.
=> Make reductionInferShape conservative to fix gorgonia#384

differentiation.go, op_math.go, solvers.go
Due to the bug in tensor.Mul when gorgonia/tensor#70, the AdamSolver/VanillaSolver/Momentum  are affected when using scalar as the first argument in tensor.Mul call.
Including some cleanup of typos and unused commented out code.
=> Fix solver not updating weights correctly

.github/workflows/go.yml
~This action test with GOPATH on Linux amd64~ This does not work 
Then it test with gomodules on linux / darwin / amd64 / arm
=> feat: attempt for a github action

gorgonia.go, gorgonia_test.go
=> Check Let inputs

op_tensor.go
It should still work since the val is reshaped in the next line, so the
geometry of the shape is not important at this point
=> Fix shape check when applying reshape op

op_sparsemax.go
sorry, I didn't catch this in my previous PR
=> Fix sparsemax when using a matrix as input

nn.go, nn_test.go
It can be done with just one function for both 1d and 2d batch norms.
=> Remove BatchNorm1d function

const.go, nn.go
1. Fix formula in comment
2. Fix log(1-prob) with something like log(1.000001-prob), if not that the loss func will got NaN in some rare case. I have test that in my code https://github.com/auxten/edgeRec/blob/main/model/din/model.go#L58
=> Fix BinaryXent got NaN and also formula comment

example_linalg_test.go, operatorLinAlg.go
Fixed https://github.com/gorgonia/gorgonia/issues/552
Three things in BatchedMatMul function included.
When BatchedMatMul is performed on matrix with (1, 1) shape, it will return error as the Slice operation will return a scalar as the operand. This will cause matrix multiplication requirements invalid.
Originally if the matrix C for result of matrix A x B is nil, its shape will be set to pre-defined A.row and B.col. But if transpose flag is set for either A or B, the matrix for C will be set incorrectly as it doesn't consider the transposition.
Fix incorrect newShape for matrix C re-uses the slice backing data by adding Clone for newShape.
=>  Fix BatchedMatMul bugs
